### ISSUE TITLE
error

### ISSUE THREAD

**Issue by accusable** [phishontop/proxy-scraper#2]
always getting hit w "ratelimited" when I haven't even done anything.

**Comment by phishontop** [comment]
fixed try now, just a issue with the html scraper

**Comment by accusable** [comment]
> fixed try now, just a issue with the html scraper

still doesn't work.

**Comment by phishontop** [comment]
do you have everything needed pip installed?

**Comment by accusable** [comment]
> do you have everything needed pip installed?

yea
